//
//  SessionPDFExporterTests.swift
//  AnchorTests
//
//  Tests for PDF export generation.
//

import PDFKit
import SwiftData
import UIKit
import XCTest

@testable import Anchor

@MainActor
final class SessionPDFExporterTests: XCTestCase {

    var container: ModelContainer!
    var session: Session!

    override func setUpWithError() throws {
        let schema = Schema([Session.self])
        let config = ModelConfiguration(isStoredInMemoryOnly: true)
        container = try ModelContainer(for: schema, configurations: config)

        session = Session(timestamp: Date())
        session.narrativeSummary = "A good session."
        session.moodBefore = 3
        session.moodAfter = 4
        session.moodStartDescription = "Anxious"
        session.moodEndDescription = "Calm"
        session.keyInsight = "Breathing helps."
        session.copingStrategiesExplored = ["Box breathing"]
        session.primaryFocus = "Work anxiety"
        session.relatedThemes = ["performance pressure", "sleep"]
        session.patternRecognized = "Fear spikes before manager feedback."
        session.actionItemsForUser = ["Take two breathing pauses tomorrow."]
        session.crisisRiskDetectedByModel = false
        session.primaryCopingStyle = "Cognitive reframing"
        session.sessionEffectivenessSelfRating = 7

        container.mainContext.insert(session)
    }

    func testCreatePDF_ReturnsValidData() {
        let payload = SessionSummaryPayload(session: session)
        let url = SessionPDFExporter.generatePDF(from: payload)

        XCTAssertNotNil(url)
        guard let url else { return }
        defer { try? FileManager.default.removeItem(at: url) }

        let data = try? Data(contentsOf: url)
        XCTAssertNotNil(data)
        guard let data else { return }
        XCTAssertGreaterThan(data.count, 0)

        // PDF header check
        let header = String(data: data.prefix(4), encoding: .ascii)
        XCTAssertEqual(header, "%PDF")
    }

    func testCreatePDF_ContainsExpectedSections() {
        session.suggestedFollowUp = "Bring this pattern to therapy."
        session.homework = "Try 4-7-8 breathing twice this week."

        let payload = SessionSummaryPayload(session: session)
        let url = SessionPDFExporter.generatePDF(from: payload)

        XCTAssertNotNil(url)
        guard let url else { return }
        defer { try? FileManager.default.removeItem(at: url) }

        guard
            let document = PDFDocument(url: url),
            let text = document.string
        else {
            XCTFail("Unable to read generated PDF text")
            return
        }

        let normalized = text.lowercased()
        XCTAssertTrue(normalized.contains("session notes"))
        XCTAssertTrue(normalized.contains("what we discussed"))
        XCTAssertTrue(normalized.contains("mood journey"))
        XCTAssertTrue(normalized.contains("key insight"))
        XCTAssertTrue(normalized.contains("action items for you"))
        XCTAssertTrue(normalized.contains("clinical observations"))
        XCTAssertTrue(normalized.contains("recurring patterns"))
        XCTAssertTrue(normalized.contains("generated by anchor"))
        XCTAssertTrue(normalized.contains("page 1"))
        XCTAssertTrue(normalized.contains("supportive notes"))
        XCTAssertTrue(
            normalized.contains("mood: 3/5 → 4/5")
                || normalized.contains("mood: 3/5 -> 4/5")
        )
    }

    func testCreatePDF_SafetyBannerRenderedWhenRiskDetected() {
        session.crisisRiskDetectedByModel = true
        session.crisisNotes = "Client expressed hopelessness."
        session.protectiveFactors = ["Supportive family", "Active in therapy"]
        session.safetyRecommendation = "Discuss with therapist immediately."

        let payload = SessionSummaryPayload(session: session)
        let url = SessionPDFExporter.generatePDF(from: payload)

        XCTAssertNotNil(url)
        guard let url else { return }
        defer { try? FileManager.default.removeItem(at: url) }

        guard
            let document = PDFDocument(url: url),
            let text = document.string
        else {
            XCTFail("Unable to read generated PDF text")
            return
        }

        let normalized = text.lowercased()
        XCTAssertTrue(normalized.contains("safety assessment"))
        XCTAssertTrue(normalized.contains("risk detected: yes"))
        XCTAssertTrue(normalized.contains("protective factors"))
    }

    func testCreatePDF_HandlesMissingOptionals() {
        let emptySession = Session(timestamp: Date())
        container.mainContext.insert(emptySession)
        let payload = SessionSummaryPayload(session: emptySession)

        let url = SessionPDFExporter.generatePDF(from: payload)
        XCTAssertNotNil(url)
        guard let url else { return }
        defer { try? FileManager.default.removeItem(at: url) }

        let data = try? Data(contentsOf: url)
        XCTAssertNotNil(data)
        XCTAssertGreaterThan(data?.count ?? 0, 0)

        guard
            let document = PDFDocument(url: url),
            let text = document.string
        else {
            XCTFail("Unable to read generated PDF text")
            return
        }
        let normalized = text.lowercased()
        XCTAssertTrue(normalized.contains("session notes"))
        XCTAssertTrue(normalized.contains("no notes available for this session"))
    }
}
